header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: CloudWeGo Authors

  paths:
    - '**/*.go'
    - '**/*.s'

  paths-ignore:
    - pkg/proc/eval.go
    - pkg/proc/mem.go
    - pkg/proc/protobuf.go
    - pkg/proc/region.go
    - pkg/proc/variables.go
    - pkg/proc/mapiter.go
    - testdata

  comment: on-failure